/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as ContestRouteImport } from './routes/contest'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as HomeRouteImport } from './routes/home'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as PriceScanRouteImport } from './routes/price-scan'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SubstituteRouteImport } from './routes/substitute'
import { Route as MessagesDeviceIdRouteImport } from './routes/messages.$deviceId'
import { Route as ProfileDeviceIdRouteImport } from './routes/profile.$deviceId'
import { Route as RecipeSlugRouteImport } from './routes/recipe.$slug'
import { Route as ScanIndexRouteImport } from './routes/scan.index'
import { Route as ScanCameraRouteImport } from './routes/scan.camera'
import { Route as ScanResultsRouteImport } from './routes/scan.results'
import { Route as FestivalIdIndexRouteImport } from './routes/festival.$id.index'
import { Route as FestivalIdRecipeRouteImport } from './routes/festival.$id.$recipe'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const ContestRoute = ContestRouteImport.update({
  id: '/contest',
  path: '/contest',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const PriceScanRoute = PriceScanRouteImport.update({
  id: '/price-scan',
  path: '/price-scan',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SubstituteRoute = SubstituteRouteImport.update({
  id: '/substitute',
  path: '/substitute',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesDeviceIdRoute = MessagesDeviceIdRouteImport.update({
  id: '/messages/$deviceId',
  path: '/messages/$deviceId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileDeviceIdRoute = ProfileDeviceIdRouteImport.update({
  id: '/profile/$deviceId',
  path: '/profile/$deviceId',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipeSlugRoute = RecipeSlugRouteImport.update({
  id: '/recipe/$slug',
  path: '/recipe/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanIndexRoute = ScanIndexRouteImport.update({
  id: '/scan/',
  path: '/scan/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanCameraRoute = ScanCameraRouteImport.update({
  id: '/scan/camera',
  path: '/scan/camera',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanResultsRoute = ScanResultsRouteImport.update({
  id: '/scan/results',
  path: '/scan/results',
  getParentRoute: () => rootRouteImport,
} as any)
const FestivalIdIndexRoute = FestivalIdIndexRouteImport.update({
  id: '/festival/$id/',
  path: '/festival/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const FestivalIdRecipeRoute = FestivalIdRecipeRouteImport.update({
  id: '/festival/$id/$recipe',
  path: '/festival/$id/$recipe',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/community': typeof CommunityRoute
  '/contest': typeof ContestRoute
  '/favorites': typeof FavoritesRoute
  '/home': typeof HomeRoute
  '/inbox': typeof InboxRoute
  '/price-scan': typeof PriceScanRoute
  '/settings': typeof SettingsRoute
  '/substitute': typeof SubstituteRoute
  '/messages/$deviceId': typeof MessagesDeviceIdRoute
  '/profile/$deviceId': typeof ProfileDeviceIdRoute
  '/recipe/$slug': typeof RecipeSlugRoute
  '/scan/camera': typeof ScanCameraRoute
  '/scan/results': typeof ScanResultsRoute
  '/scan/': typeof ScanIndexRoute
  '/festival/$id/$recipe': typeof FestivalIdRecipeRoute
  '/festival/$id/': typeof FestivalIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/community': typeof CommunityRoute
  '/contest': typeof ContestRoute
  '/favorites': typeof FavoritesRoute
  '/home': typeof HomeRoute
  '/inbox': typeof InboxRoute
  '/price-scan': typeof PriceScanRoute
  '/settings': typeof SettingsRoute
  '/substitute': typeof SubstituteRoute
  '/messages/$deviceId': typeof MessagesDeviceIdRoute
  '/profile/$deviceId': typeof ProfileDeviceIdRoute
  '/recipe/$slug': typeof RecipeSlugRoute
  '/scan/camera': typeof ScanCameraRoute
  '/scan/results': typeof ScanResultsRoute
  '/scan': typeof ScanIndexRoute
  '/festival/$id/$recipe': typeof FestivalIdRecipeRoute
  '/festival/$id': typeof FestivalIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/community': typeof CommunityRoute
  '/contest': typeof ContestRoute
  '/favorites': typeof FavoritesRoute
  '/home': typeof HomeRoute
  '/inbox': typeof InboxRoute
  '/price-scan': typeof PriceScanRoute
  '/settings': typeof SettingsRoute
  '/substitute': typeof SubstituteRoute
  '/messages/$deviceId': typeof MessagesDeviceIdRoute
  '/profile/$deviceId': typeof ProfileDeviceIdRoute
  '/recipe/$slug': typeof RecipeSlugRoute
  '/scan/camera': typeof ScanCameraRoute
  '/scan/results': typeof ScanResultsRoute
  '/scan/': typeof ScanIndexRoute
  '/festival/$id/$recipe': typeof FestivalIdRecipeRoute
  '/festival/$id/': typeof FestivalIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/community'
    | '/contest'
    | '/favorites'
    | '/home'
    | '/inbox'
    | '/price-scan'
    | '/settings'
    | '/substitute'
    | '/messages/$deviceId'
    | '/profile/$deviceId'
    | '/recipe/$slug'
    | '/scan/camera'
    | '/scan/results'
    | '/scan/'
    | '/festival/$id/$recipe'
    | '/festival/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/community'
    | '/contest'
    | '/favorites'
    | '/home'
    | '/inbox'
    | '/price-scan'
    | '/settings'
    | '/substitute'
    | '/messages/$deviceId'
    | '/profile/$deviceId'
    | '/recipe/$slug'
    | '/scan/camera'
    | '/scan/results'
    | '/scan'
    | '/festival/$id/$recipe'
    | '/festival/$id'
  id:
    | '__root__'
    | '/'
    | '/community'
    | '/contest'
    | '/favorites'
    | '/home'
    | '/inbox'
    | '/price-scan'
    | '/settings'
    | '/substitute'
    | '/messages/$deviceId'
    | '/profile/$deviceId'
    | '/recipe/$slug'
    | '/scan/camera'
    | '/scan/results'
    | '/scan/'
    | '/festival/$id/$recipe'
    | '/festival/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CommunityRoute: typeof CommunityRoute
  ContestRoute: typeof ContestRoute
  FavoritesRoute: typeof FavoritesRoute
  HomeRoute: typeof HomeRoute
  InboxRoute: typeof InboxRoute
  PriceScanRoute: typeof PriceScanRoute
  SettingsRoute: typeof SettingsRoute
  SubstituteRoute: typeof SubstituteRoute
  MessagesDeviceIdRoute: typeof MessagesDeviceIdRoute
  ProfileDeviceIdRoute: typeof ProfileDeviceIdRoute
  RecipeSlugRoute: typeof RecipeSlugRoute
  ScanCameraRoute: typeof ScanCameraRoute
  ScanResultsRoute: typeof ScanResultsRoute
  ScanIndexRoute: typeof ScanIndexRoute
  FestivalIdRecipeRoute: typeof FestivalIdRecipeRoute
  FestivalIdIndexRoute: typeof FestivalIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contest': {
      id: '/contest'
      path: '/contest'
      fullPath: '/contest'
      preLoaderRoute: typeof ContestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/price-scan': {
      id: '/price-scan'
      path: '/price-scan'
      fullPath: '/price-scan'
      preLoaderRoute: typeof PriceScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/substitute': {
      id: '/substitute'
      path: '/substitute'
      fullPath: '/substitute'
      preLoaderRoute: typeof SubstituteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages/$deviceId': {
      id: '/messages/$deviceId'
      path: '/messages/$deviceId'
      fullPath: '/messages/$deviceId'
      preLoaderRoute: typeof MessagesDeviceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$deviceId': {
      id: '/profile/$deviceId'
      path: '/profile/$deviceId'
      fullPath: '/profile/$deviceId'
      preLoaderRoute: typeof ProfileDeviceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipe/$slug': {
      id: '/recipe/$slug'
      path: '/recipe/$slug'
      fullPath: '/recipe/$slug'
      preLoaderRoute: typeof RecipeSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan/': {
      id: '/scan/'
      path: '/scan'
      fullPath: '/scan/'
      preLoaderRoute: typeof ScanIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan/camera': {
      id: '/scan/camera'
      path: '/scan/camera'
      fullPath: '/scan/camera'
      preLoaderRoute: typeof ScanCameraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan/results': {
      id: '/scan/results'
      path: '/scan/results'
      fullPath: '/scan/results'
      preLoaderRoute: typeof ScanResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/festival/$id/': {
      id: '/festival/$id/'
      path: '/festival/$id'
      fullPath: '/festival/$id/'
      preLoaderRoute: typeof FestivalIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/festival/$id/$recipe': {
      id: '/festival/$id/$recipe'
      path: '/festival/$id/$recipe'
      fullPath: '/festival/$id/$recipe'
      preLoaderRoute: typeof FestivalIdRecipeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CommunityRoute: CommunityRoute,
  ContestRoute: ContestRoute,
  FavoritesRoute: FavoritesRoute,
  HomeRoute: HomeRoute,
  InboxRoute: InboxRoute,
  PriceScanRoute: PriceScanRoute,
  SettingsRoute: SettingsRoute,
  SubstituteRoute: SubstituteRoute,
  MessagesDeviceIdRoute: MessagesDeviceIdRoute,
  ProfileDeviceIdRoute: ProfileDeviceIdRoute,
  RecipeSlugRoute: RecipeSlugRoute,
  ScanCameraRoute: ScanCameraRoute,
  ScanResultsRoute: ScanResultsRoute,
  ScanIndexRoute: ScanIndexRoute,
  FestivalIdRecipeRoute: FestivalIdRecipeRoute,
  FestivalIdIndexRoute: FestivalIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
